'use client'

import { useState } from 'react'
import { ChevronDown } from 'lucide-react'
import type { Insight } from '@/lib/dummy-content'

/**
 * Collapsible "AI Insights" strip from the Fulltiime design — context a casual
 * fan might be missing, surfaced above the article body.
 */
export function AiInsights({ insights }: { insights: Insight[] }) {
  const [open, setOpen] = useState(false)
  if (insights.length === 0) return null

  return (
    <div className="mb-7.5 overflow-hidden rounded-[14px] border border-[rgba(29,185,84,0.32)] bg-linear-[120deg] from-[rgba(29,185,84,0.1)] to-primary/5">
      <button
        onClick={() => setOpen((o) => !o)}
        className="flex w-full items-center gap-3 px-4.5 py-3.75 text-left text-foreground"
      >
        <span className="flex h-7.5 w-7.5 shrink-0 items-center justify-center rounded-lg bg-[var(--green)] text-[15px] font-bold text-[#04140a]">
          ✦
        </span>
        <span className="flex-1">
          <span className="block text-[14px] font-bold text-head">AI Insights</span>
          <span className="block font-mono text-[12px] text-[#9FD9B4]">
            context a casual fan might be missing
          </span>
        </span>
        <ChevronDown
          className={`h-4 w-4 text-[#9FD9B4] transition-transform duration-250 ${open ? 'rotate-180' : ''}`}
        />
      </button>
      {open && (
        <div className="flex flex-col gap-3 px-4.5 pt-1 pb-5">
          {insights.map((ins) => (
            <div key={ins.l} className="flex items-start gap-3">
              <span className="mt-0.5 shrink-0 rounded-[5px] bg-primary px-2 py-1 font-mono text-[10px] font-bold tracking-[0.08em] text-primary-foreground">
                {ins.l}
              </span>
              <p className="m-0 text-[14px] leading-normal text-foreground">{ins.t}</p>
            </div>
          ))}
          <div className="mt-1 border-t border-border pt-2 font-mono text-[11px] text-muted-foreground">
            Generated by Fulltiime AI · always double-check the big claims
          </div>
        </div>
      )}
    </div>
  )
}
